# Site Config
title: Reddit Enhancement Suite
author: RES Team
description: Reddit Enhancement Suite (RES) is a community-driven unofficial browser extension for enhancing your reddit experience.
short_description: community-driven unofficial browser extension for reddit
google_analytics: UA-17650786-1
permalink: pretty

# Versions
chrome_version: v5.18.12
firefox_version: v5.18.12
